services:
  db:
    build: ./deploy/local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432

  db-testing:
    build: ./deploy/local
    environment:
      POSTGRES_DB: testing
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  nats:
    image: "nats-streaming:0.9.2"
  elastichsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.8"
    enviroment:
      - DISCOVERY_TYPE=single-node
  feed:
    build: .
    command: "feed-service"
    depends_on:
      - "db"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      NATS_ADDRESS: "nats:4222"
  pusher:
    build: "."
    command: "pusher-service"
    depends_on:
      - "nats"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"
  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - feed
      - query
      - pusher